baseURL = "https://otokunaga2.github.io/"
languageCode = "ja-jp"
title = "Look back on myself"
theme = "hugo-classic"
enableEmoji = true
footnotereturnlinkcontents = "↩"

# Required to get well formatted code blocks
# Following options are referenced by
# https://geekdocs.de/usage/configuration/#site-configuration
# Geekblog required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 1
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

